#!usr/bin/python3
def raise_exception_msg("");
    raise NameError(message)
